# @package _global_

defaults:
  - legged_base

# Env structure
env:
  _target_: humanoidverse.envs.decoupled_locomotion.decoupled_locomotion_stand_height_waist_wbc_ma_diff_force.LeggedRobotDecoupledLocomotionStanceHeightWBCForce
  config:
    max_episode_length_s: 20
    locomotion_obs_scales:
      lin_vel: 1.0
      ang_vel: 1.0
      dof_pos: 1.0
      dof_vel: 1.0
      humanoid_commands_scale: 1.0
    locomotion_command_ranges:
      lin_vel_x: [-1.0, 1.0]
      lin_vel_y: [-1.0, 1.0]
      ang_vel_yaw: [-1.0, 1.0]
      heading: [-3.14, 3.14]
      base_height: [-0.25, 0.0]
      # base_height: [-0.0, 0.0]
    stand_prob: 0.4
    tapping_in_place_prob: 0.0
    # Upper body waist motion setting
    fix_upper_body_prob: 0.3
    apply_waist_roll_only_when_stance: True
    apply_waist_pitch_only_when_stance: True
    apply_waist_yaw_only_when_stance: True
    fix_waist_yaw: True
    fix_waist_roll: True
    fix_waist_pitch: True
    fix_waist_yaw_range: [-1.0, 1.0]
    fix_waist_roll_range: [-0.0, 0.0]
    fix_waist_pitch_range: [-0.0, 0.0]
    zero_fix_waist_yaw_prob: 0.1
    zero_fix_waist_roll_prob: 1.0
    zero_fix_waist_pitch_prob: 1.0
    # Upper body motion resampling
    resample_motion_when_training: True
    resample_time_interval_s: 2000
    # Locomotion command resampling
    locomotion_command_resampling_time: 10.0
    obs_history:
      history_len: 0
    
    # Residual upper body action
    residual_upper_body_action: True

    # Force 
    max_force_estimation: True
    update_apply_force_phase: True
    use_lpf: False
    force_filter_alpha: 0.05
    zero_tapping_xy_force: False
    zero_force_prob: [0.25, 0.25, 0.25] # 0.2
    random_force_prob: 0.0
    apply_force_x_range: [-40.0, 40.0]
    apply_force_y_range: [-40.0, 40.0]
    apply_force_z_range: [-50.0, 5.0]
    apply_force_pos_ratio_range: [0.0, 1.0]
    lower_body_force_compensation: False
    apply_force_in_physics_step: True
    apply_force_compensation_in_physics_step: False
    randomize_force_duration: [150, 250] # The unit is step, where policy runs at 50Hz
    only_apply_z_force_when_walking: False
    only_apply_resistance_when_walking: True

    termination:
      terminate_by_contact: False
      # terminate_by_lin_vel: False
      # terminate_by_ang_vel: False
      terminate_by_gravity: True
      terminate_by_low_height: True
      terminate_when_close_to_dof_pos_limit: False
      terminate_when_close_to_dof_vel_limit: False
      terminate_when_close_to_torque_limit: False
      terminate_when_motion_end: True
      terminate_when_low_upper_dof_tracking: False

    termination_scales:
      termination_min_base_height : 0.3
      # termination_max_base_vel : 10.0
      # termination_max_base_ang_vel : 5.0
      termination_gravity_x : 0.8
      termination_gravity_y : 0.8
      termination_close_to_dof_pos_limit : 0.98
      termination_close_to_dof_vel_limit : 0.98
      termination_close_to_torque_limit : 0.98
      terminate_when_low_upper_dof_tracking_threshold: 0.1


# Globally accessible parameters
log_task_name: decoupled_locomotion

eval_overrides:
  env:
    config: 
      max_episode_length_s: 100000
