# @package _global_

# Be careful when using _raw, history
obs:
  use_phase: True
  obs_dict:
    actor_obs: [
      # base_lin_vel,
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      command_stand,
      command_waist_dofs,
      command_base_height,
      ref_upper_dof_pos,
      dof_pos,
      dof_vel,
      actions,
      # sin_phase,
      # cos_phase,
    ]

    critic_obs: [
      base_orientation,
      base_lin_vel,
      base_ang_vel,
      projected_gravity,
      command_lin_vel,
      command_ang_vel,
      command_stand,
      command_waist_dofs,
      command_base_height,
      ref_upper_dof_pos,
      dof_pos,
      dof_vel,
      actions,
      left_ee_apply_force,
      right_ee_apply_force,
      # sin_phase,
      # cos_phase,
    ]
  
  history_length:
    actor_obs: 5
    critic_obs: 1

  obs_scales: {
    base_orientation: 1.0,
    base_lin_vel: 2.0,
    base_ang_vel: 0.25,
    projected_gravity: 1.0,
    command_lin_vel: 1.0,
    command_ang_vel: 1.0,
    command_stand: 1.0,
    command_waist_dofs: 1.0,
    command_base_height: 2.0,
    ref_upper_dof_pos: 1.0,
    dof_pos: 1.0,
    dof_vel: 0.05,
    actions: 1.0,
    sin_phase: 1.0,
    cos_phase: 1.0,
    left_ee_apply_force: 0.1,
    right_ee_apply_force: 0.1,
    history_actor: 1.0,
  }
  
  add_noise: False
  # noise_scales: {
  #   base_lin_vel: 0.0,
  #   base_ang_vel: 0.2,
  #   projected_gravity: 0.05,
  #   command_lin_vel: 0.0,
  #   command_ang_vel: 0.0,
  #   command_stand: 0.0,
  #   command_base_height: 0.0,
  #   ref_upper_dof_pos: 0.01,
  #   dof_pos: 0.01,
  #   dof_vel: 1.5, # 1.5
  #   actions: 0.0,
  #   sin_phase: 0.0,
  #   cos_phase: 0.0,
  #   phase_time: 0.0,
  #   history_actor: 0.0,
  #   history_critic: 0.0,
  # }
  noise_scales: {
    base_orientation: 0.0,
    base_lin_vel: 0.0,
    base_ang_vel: 0.0,
    projected_gravity: 0.0,
    command_lin_vel: 0.0,
    command_ang_vel: 0.0,
    command_stand: 0.0,
    command_waist_dofs: 0.0,
    command_base_height: 0.0,
    ref_upper_dof_pos: 0.0,
    dof_pos: 0.01,
    dof_vel: 0.1, # 1.5
    actions: 0.0,
    sin_phase: 0.0,
    cos_phase: 0.0,
    left_ee_apply_force: 0.0,
    right_ee_apply_force: 0.0,
    history_actor: 0.0,
  }

  # obs_dims should use list instead of dict
  # will be converted to dict in `pre_process_config`
  obs_dims:
    - base_orientation: 4
    - base_lin_vel: 3
    - base_ang_vel: 3
    - projected_gravity: 3
    - command_lin_vel: 2
    - command_ang_vel: 1
    - command_stand: 1
    - command_waist_dofs: 3
    - command_base_height: 1
    - ref_upper_dof_pos: ${robot.upper_body_actions_dim} # upper body actions
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - actions: ${robot.dof_obs_size} # wbc body actions
    - sin_phase: 1
    - cos_phase: 1
    - left_ee_apply_force: 3
    - right_ee_apply_force: 3
